CS50W_Week3/src/lecture3/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index1, name="index"),
    path("<str:name>", views.greet1, name="greet"),
    path("brian", views.brian, name="brian"),
    path("david", views.david, name="david"),
]

CS50W_Week3/src/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include("hello.urls")),
    path("tasks/", include("tasks.urls")),
    path("newyear/", include("newyear.urls")),
]

CS50W_Week3/src/lecture3/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

CS50W_Week3/src/lecture3/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
]

CS50W_Week3/src/lecture3/hello/models.py
from django.db import models

# Create your models here.

CS50W_Week3/src/lecture3/newyear/models.py
from django.db import models

# Create your models here.

CS50W_Week3/src/lecture3/tasks/models.py
from django.db import models

# Create your models here.

CS50W_Week3/src/lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index0(request):
    return HttpResponse("Hello, world!")

def index1(request):
    return render(request, "hello/index.html")

def brian(request):
    return HttpResponse("Hello, Brian!")

def david(request):
    return HttpResponse("Hello, David!")

def greet0(request, name):
    return HttpResponse(f"Hello, {name.capitalize()}!")

def greet1(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

CS50W_Week3/src/lecture3/newyear/views.py
import datetime

from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

CS50W_Week3/src/lecture3/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    # priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
    else:
        return render(request, "tasks/add.html", {
            "form": NewTaskForm()
        })

CS50W_Week3/src/lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        Hello, {{ name }}!
    </body>
</html>

CS50W_Week3/src/lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        Hello, world!
    </body>
</html>

CS50W_Week3/src/lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View All Tasks</a>
{% endblock %}

CS50W_Week3/src/lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No tasks.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add New Task</a>
{% endblock %}

CS50W_Week3/src/lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>